name: joke-generator
run-name: joke genetator
on:
  push:
    branches:
      - main
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: pull my project
        uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v2
      - name: install joke generator
        run: npm install --global @mikemcbrike/dad-jokes 
