name: Exercice git versioning
run-name: joke genetator
on:
  push:
    branches:
      - main
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run : echo "Hello, GitHub Actions!"